name: wanAndroid
description: WanAndroid 客户端 Flutter版.

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  flutter_webview_plugin: "^0.1.6"
  image_picker: "^0.4.1"
  shared_preferences: "^0.4.1"
  event_bus: "^0.4.1"


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/ic_launcher_round.png

