name: wanAndroid
description: WanAndroid 客户端 Flutter版.

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  flutter_webview_plugin: "^0.3.0+2"
  shared_preferences: "^0.4.1"
  event_bus: "^1.0.1"
  http: '>=0.11.3+12'

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/ic_launcher_round.png
    - images/ic_arrow_down.png
    - images/bg.png
    - images/bg_rect_shadow.png
    - images/bg_rect_10_shadow_yellow.png
    - images/ic_coupon_attractive.png
    - images/ic_coupon_msg_1.png
    - images/ic_coupon_msg_2.png
    - images/ic_coupon_msg_3.png
    - images/ic_status_used.png
    - images/bg_coupon_send_default.png
    - images/ic_see_white.png
    - images/ic_arrow_down_shadow.png

